title: Oleg Smirnov
description: >-
  Thoughts about development and design
baseurl: ""
url: "https://olgnet.name"
github_username:  olgnet

theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
