title: Smirnov Oleg
description: >-
  Thoughts and notes about software development
baseurl: ""
url: "https://olgnet.name"

defaults:
  # Blog posts (collection)
  - scope:
      path: "_posts"
    values:
      permalink: blog/:title/
      layout: post
  # Blog drafts
  - scope:
      path: "_drafts"
    values:
      permalink: drafts/:title/
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
